server:
  port: 8084

spring:
  datasource:
    url: jdbc:postgresql://localhost:6433/subscription_db
    username: subscription_user
    password: subscription_pass  # Replace with your actual DB password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update      # Automatically create/update tables
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false     # Recommended for REST APIs

jwt:
  secret: smart-subscription-default-secret-key-256-bit
  expiration: 500000

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
