server:
  port: 8080

jwt:
  secret: ${JWT_SECRET:smart-subscription-default-secret-key-256-bit}
  expiration: 500000

spring:
  datasource:
    url: jdbc:postgresql://localhost:6432/auth_db
    username: auth_user
    password: auth_pass
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
